import Head from "next/head";
import BasicLayout from "../../components/BasicLayout";
import React from "react";
import FeaturePlaceholder from "../../components/FeaturePlaceholder";

export default function FeatureFlag() {
    return(
        <div>
            <Head>
                <title>FeatureFlag</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <BasicLayout current_path={'/quality_platform/feature_flag'}>
                <FeaturePlaceholder />
            </BasicLayout>
        </div>
    )
}
