import Head from "next/head";
import BasicLayout from "../../components/BasicLayout";

import React, { useState } from 'react';
import PT_Summary from "../../components/PT_Summary";

export default function PerformanceTesting() {
    const [currentNav, setCurrentNav] = useState('Summary');
    return(
        <>
            <Head>
                <title>PerformanceTesting</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <BasicLayout current_path={'/quality_platform/performance_testing'}>
                <div>
                    <div className={'top_nav'}>
                        <div className={currentNav === 'Summary' ? 'nav_item_selected' : 'nav_item'}
                             onClick={()=>setCurrentNav('Summary')}>
                            <a className={currentNav === 'Summary' ? 'menu_selected' : 'menu'}>Summary</a>
                        </div>
                        <div className={currentNav === 'Runs' ? 'nav_item_selected' : 'nav_item'}
                             onClick={()=>setCurrentNav('Runs')}>
                            <a className={currentNav === 'Runs' ? 'menu_selected' : 'menu'}>Runs</a>
                        </div>
                        <div className={currentNav === 'Historical runs' ? 'nav_item_selected' : 'nav_item'}
                             onClick={()=>setCurrentNav('Historical runs')}>
                            <a className={currentNav === 'Historical runs' ? 'menu_selected' : 'menu'}>Historical runs</a>
                        </div>
                    </div>
                    <div className={'sub_page'}>
                        {currentNav === 'Summary' && <PT_Summary />}
                    </div>
                </div>
            </BasicLayout>
            <style jsx>{`
                .top_nav {
                    display:flex;
                    padding: 20px;
                }
                
                .nav_item {
                    margin: 10px 20px;
                    padding: 6px 0;
                }
                
                .nav_item_selected {
                    margin: 10px 20px;
                    padding: 6px 0;
                    border-bottom: 2px solid #5139f2;
                }
                
                .menu {
                    color: #1f1f1f;
                }
                .menu_selected {
                    color: #5139f2;
                    
                }
            `}
            </style>
        </>
    )
}
