import Head from "next/head";
import React, { useState, useEffect } from 'react';
import {ResponsiveContainer, LineChart, XAxis, Tooltip, CartesianGrid, Line, YAxis} from "recharts";
import BasicLayout from "../../components/BasicLayout";
export default function Hello() {
    const [data, setData] = useState([])
    const [testData, setTestData] = useState([])
    useEffect(async ()=>{
        const ret = await fetch('/lg/api/get')
        const retJson = await ret.json()
        setTestData(retJson['account_detail'])
        setData(retJson)
        console.log(retJson)
    }, [])

    return (
        <div>
            <Head>
                <title>Webapp performance</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <BasicLayout current_path={'/quality_platform/lighthouse'}>
                <div style={{padding:'30px'}}>
                    {
                        Object.keys(data).map((key, index) => (
                            <div style={{padding:'30px'}}>
                                <div>{key}</div>
                                <ResponsiveContainer
                                    width={'100%'}
                                    height={400}
                                >
                                    <LineChart
                                        data={data[key]}
                                        margin={{left:50, top:50, right:50}}
                                    >
                                        <Tooltip/>
                                        <CartesianGrid stroke="#eee" strokeDasharray="5 5"/>
                                        <Line type="monotone" dataKey="performance" stroke="#ff7300"/>
                                        <Line type="monotone" dataKey="accessibility" stroke="#ff0073"/>
                                        <Line type="monotone" dataKey="best-practices" stroke="#0073ff"/>
                                        <XAxis dataKey="date" />
                                        <YAxis />
                                    </LineChart>
                                </ResponsiveContainer>
                            </div>
                        ))
                    }
                </div>
            </BasicLayout>
        </div>

    )
}
